### ISSUE TITLE
Missing support for php 7.2

### ISSUE THREAD

**Issue by gergnz** [awslabs/aws-elasticache-cluster-client-memcached-for-php#19]
I'm not able to use the php7 branch to build against php7.2. While the build completes, the shared object can't be loaded due to a missing symbol, which looks to have changed between php 7.1 and php 7.2: strpprintf

**Comment by sodabrew** [comment]
See #11 for instructions on how to compile – Both PHP 7.1 and 7.2 are supported by the underlying modules, however binaries are provided by Amazon only for PHP 7.0 at this time.

**Comment by gergnz** [comment]
I've tried and it's not working. (see my comments re missing symbol strpprintf). It looks like this has changed in zend, and my C isn't good enough to understand what's going on.

Also this comment (https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/issues/11#issuecomment-373426823) suggests that it isn't working for others.

**Comment by QuChen88** [comment]
I just managed to install PHP 7.2 on ubuntu 16.04 and compile the client based on libmemcached 1.0.8. In case you need the binary to get unblocked, here it is. Let me know if this works for you or not. 

[AmazonElasticacheClusterClient-PHP72-64bit-libmemcached-1.0.8.tar.gz](https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/files/1993851/AmazonElasticacheClusterClient-PHP72-64bit-libmemcached-1.0.8.tar.gz)

**Comment by markhughes** [comment]
@QuChen88 tested on PHP Version 7.2.5-1+ubuntu16.04.1 and it seems to be connecting and doing basics. Will have a better play later.

**Comment by agaleski** [comment]
On `PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1` via _ppa:ondrej/php_ copy the _amazon-elasticache-cluster-client.so_ from @QuChen88 (https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/issues/19#issuecomment-388247756) to `/usr/lib/php/20170718/` so php7.2-fpm can find it

**Comment by elyobo** [comment]
Part way through upgrading to PHP 7.2 on Amazon Linux and :bomb: :boom: turns out that AWS doesn't provide a client yet :-/

**Comment by elyobo** [comment]
That said, @QuChen88's version above does seem to work for me on the latest Amazon Linux; any news when an "official" version would be available?

**Comment by elyobo** [comment]
Addendum, we're seeing a lot of logs with `Unknown: using touch command with binary protocol is not recommended with libmemcached versions below 1.0.18, please use ascii protocol or upgrade libmemcached` with @QuChen88's package above.  @QuChen88, given the comments on https://github.com/php-memcached-dev/php-memcached/issues/310 and https://github.com/php-memcached-dev/php-memcached/pull/322 it seems like compiling against a newer libmemcached is probably required to support the default PHP7 behaviour (lazy write enabled).

**Comment by putchi** [comment]
> I just managed to install PHP 7.2 on ubuntu 16.04 and compile the client based on libmemcached 1.0.8. In case you need the binary to get unblocked, here it is. Let me know if this works for you or not.
> 
> [AmazonElasticacheClusterClient-PHP72-64bit-libmemcached-1.0.8.tar.gz](https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/files/1993851/AmazonElasticacheClusterClient-PHP72-64bit-libmemcached-1.0.8.tar.gz)

This worked for me.
OS: ubuntu 18 latest
* php info: 
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

@gergnz  you should close this issue for the best answer of @QuChen88

**Comment by sodabrew** [comment]
As the maintainer of the php-memcached module on which this work is based, I must urge against using older versions of libmemcached with known bugs and deficiencies.

What is the problem that is blocking the AWS modifications to libmemcached 1.0.18 from being used here?

**Comment by gergnz** [comment]
@sodabrew, can you advise on these upstream changes please?

**Comment by sodabrew** [comment]
Read five comments back, the error message says to use an updated library to avoid a specific bug. That text is meant to be as clear as possible in people’s error logs.

**Comment by liaogz82** [comment]
is there an aws elastic client memcached for PHP 7.2 in amazon linux?

**Comment by putchi** [comment]
> is there an aws elastic client memcached for PHP 7.2 in amazon linux?
Read my comment above. @QuChen88 comment worked for me.

**Comment by elyobo** [comment]
It "works" for certain values of "works"; the stream of warnings reporting about `Unknown: using touch command with binary protocol is not recommended with libmemcached versions below 1.0.18, please use ascii protocol or upgrade libmemcached` is concerning and @sodabrew's (maintainer of the upstream `php-memcached`) comments also suggest that this issue is not properly resolved.

To resolve this

* update libmemcached
* do a proper release with it, not just a comment in an issue
* have it downloadable through the AWS console as per other releases

**Comment by liaogz82** [comment]
> > is there an aws elastic client memcached for PHP 7.2 in amazon linux?
> > Read my comment above. @QuChen88 comment worked for me.

@QuChen88 answer is for debian OS. what about amazon linux?

**Comment by elyobo** [comment]
My comments above are from using it on Amazon Linux @liaogz82; it installs and appears to work, but has a stream of warnings in the logs and the impact of that isn't clear to me.

**Comment by liaogz82** [comment]
@elyobo how do you get the logs? I managed to get it working and on the surface seems to be ok

**Comment by elyobo** [comment]
Wherever your PHP logs go, and presumably also dependent on your [error_reporting](https://secure.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) settings.

**Comment by luishdz1010** [comment]
Here's a Dockerfile for compiling on 7.2

```Dockerfile
FROM centos:7

RUN yum -y install epel-release
RUN yum -y update
RUN yum install -y wget git
RUN wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN rpm -Uvh remi-release-7.rpm
RUN yum-config-manager --enable remi-php72
RUN yum update

RUN yum install -y php php-cli gcc gcc-c++ autoconf libevent-devel php-devel zlib-devel make

RUN mkdir /tmp/libmemcached \
    && cd /tmp/libmemcached \
    && git clone https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached.git

RUN cd /tmp/libmemcached/aws-elasticache-cluster-client-libmemcached \
    && touch configure.ac aclocal.m4 configure Makefile.am Makefile.in \
    && mkdir BUILD

WORKDIR /tmp/libmemcached/aws-elasticache-cluster-client-libmemcached/build

RUN ../configure --prefix=/tmp/libmemcached --with-pic
RUN make
RUN make install

WORKDIR /usr/lib64
RUN ln libsasl2.so.3 libsasl2.so.2
RUN ln libsasl2.so.3 libsasl2.so

RUN cd /tmp \
    && git clone https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php.git \
    && cd aws-elasticache-cluster-client-memcached-for-php/ \
    && git checkout php7

WORKDIR /tmp/aws-elasticache-cluster-client-memcached-for-php/

RUN phpize
RUN ./configure --with-libmemcached-dir=/tmp/libmemcached --disable-memcached-sasl
RUN sed -i "s#-lmemcached#/tmp/libmemcached/lib/libmemcachedutil.a /tmp/libmemcached/lib/libmemcached.a -lcrypt -lpthread -lm -lstdc++ -lsasl2#" Makefile
RUN sed -i "s#-lmemcachedutil##" Makefile
RUN sed -i "s#-L/tmp/libmemcached/lib##" Makefile
RUN make
```

**Comment by QuChen88** [comment]
@Seegras  IIRC, I compiled it following the instructions I had in the README.markdown file. I launched an EC2 instance from AWS console using the standard Ubuntu AMI.

**Comment by WillyYeh** [comment]
Many thanks to @luishdz1010. I followed your Dockerfile and build my own RPM and PEAR package.
Follow these steps to build our own RPMS and PER package.

* Prepare the building environment.
Create a development environment which are same as production environment. For example, m5.medium in EC2. And limit the max hosts to 1 if your are using Elastic Beanstalk.
```sh
export HOME=/home/ec2-user
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
sudo yum -y install rpm-build java-1.8.0-openjdk
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
echo "%packager You <your@email>" >> ~/.rpmmacros
mkdir ~/src
```

* Build libmemcached RPM
Create your own libmemcached.spec before running below commands.
```sh
cd ~/src
sudo yum install -y libevent-devel
wget https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached/archive/v1.0.18.tar.gz
tar zxf v1.0.18.tar.gz
cd aws-elasticache-cluster-client-libmemcached-1.0.18 && mkdir BUILD && cd BUILD
../configure --prefix=/usr --libdir=/usr/lib64 --with-pic && make && make DESTDIR=/home/ec2-user/rpmbuild/SOURCES/libmemcached-1.0.18 install
cd ~/rpmbuild/SOURCES
rm libmemcached-1.0.18/usr/lib64/*.la
tar zcf libmemcached-1.0.18.tar.gz libmemcached-1.0.18
sed -i '/^%defattr/,$d' ../SPECS/libmemcached.spec && echo -e "%defattr(-,root,root,-)" >> ../SPECS/libmemcached.spec && find libmemcached-1.0.18 ! -type d ! \( -path 'libmemcached-1.0.18/usr/include/*' -o -path 'libmemcached-1.0.18/usr/lib64/pkgconfig/*' -o -path 'libmemcached-1.0.18/usr/share/man/man3/*' -o -path 'libmemcached-1.0.18/usr/share/aclocal/*' -o -path 'libmemcached-1.0.18/usr/lib64/*' \) -o -path 'libmemcached-1.0.18/usr/lib64/*.so.*' -o -path 'libmemcached-1.0.18/usr/lib64/*.a' | sed 's/^[^\/]*\//\//g' >> ../SPECS/libmemcached.spec && echo -e "\n%files devel\n%defattr(-,root,root,-)" >> ../SPECS/libmemcached.spec && find libmemcached-1.0.18 ! -type d \( -path 'libmemcached-1.0.18/usr/include/*' -o -path 'libmemcached-1.0.18/usr/lib64/pkgconfig/*' -o -path 'libmemcached-1.0.18/usr/share/man/man3/*' -o -path 'libmemcached-1.0.18/usr/share/aclocal/*' -o -path 'libmemcached-1.0.18/usr/lib64/*.so' \) | sed 's/^[^\/]*\//\//g' >> ../SPECS/libmemcached.spec
vi ../SPECS/libmemcached.spec
rm -rf libmemcached-1.0.18
rpmbuild -bb ../SPECS/libmemcached.spec
sudo rpm -Uvh ../RPMS/x86_64/libmemcached-1.0.18-1.amzn1.x86_64.rpm ../RPMS/x86_64/libmemcached-devel-1.0.18-1.amzn1.x86_64.rpm
```

* Build ElastiCache Cluster Client for PHP PEAR package.
Download AmazonElastiCacheClusterClient-1.0.0-PHP70-64bit.tgz from AWS ElastiCache Client for PHP webpage. Untar it and then change folder name to AmazonElastiCacheClusterClient-2.0.3 if you like. Remember you have to update the md5 of modules/memcached.so in package.xml.
```sh
cd ~/src
sudo yum install -y cyrus-sasl-devel php72-pecl-igbinary-devel
git clone https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php.git && cd aws-elasticache-cluster-client-memcached-for-php/ && git checkout php7
phpize
./configure --disable-memcached-sasl --enable-memcached-igbinary --with-libmemcached-dir=/usr && make
tar zxf <somewhere>/AmazonElastiCacheClusterClient-2.0.3-PHP72-64bit.tgz
cp modules/memcached.so AmazonElastiCacheClusterClient-2.0.3/amazon-elasticache-cluster-client.so
vi package.xml
rm AmazonElastiCacheClusterClient-2.0.3-PHP72-64bit.tgz && tar zcf AmazonElastiCacheClusterClient-2.0.3-PHP72-64bit.tgz package.xml AmazonElastiCacheClusterClient-2.0.3/
```

Now you can install by `pecl7 install AmazonElastiCacheClusterClient-2.0.3-PHP72-64bit.tgz`
PS: You may get an error which related to `/usr/share/pear7/Archive/Tar.php`
Just run below command:
`sed -i '639s/$v_att_list = & func_get_args();/\\$v_att_list \\&= func_get_args();/' /usr/share/pear7/Archive/Tar.php`

**Comment by ninjada** [comment]
Second jswinborne's comments. Been waiting for what seems like forever for this -- compilings not the end of the world but have had it cause a couple of hiccups with my moves to Amazon Linux 2. 

I would have thought the amazon-linux-extras option would have been perfect for this? Given its intended ease of use is somewhat logically questionable in the first place.

**Comment by elyobo** [comment]
@QuChen88 is this project officially supported by AWS?  It's in the `awslabs` account and you're a member of the `Amazon Web Services` org, so I've been assuming so, but given the lack of any activity in supporting the PHP versions available on AWS's own "Amazon Linux" distro I may have misunderstood?

**Comment by nkhine** [comment]
i managed to get it working under docker https://github.com/nkhine/centos-nginx-php72-fpm/blob/master/Dockerfile

using https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.2/latest-64bit

**Comment by QuChen88** [comment]
PHP 7.2 is now supported and downloadable from AWS console.

**Comment by bensebborn** [comment]
@QuChen88 is this 7.2 .so file compiled against libmemcached 1.0.8 or 1.0.18?

**Comment by yzhaon** [comment]
> @QuChen88 is this 7.2 .so file compiled against libmemcached 1.0.8 or 1.0.18?

The PHP 7.2 memcached client is now compiled against libmemcached 1.0.18.

Please update if you had an older version.
