### ISSUE TITLE
Broken backward compatibility between PHP 7.0 and 7.2 ElastiCache clients with consistent distribution

### ISSUE THREAD

**Issue by antydemant** [awslabs/aws-elasticache-cluster-client-memcached-for-php#28]
If you are downloading ElastiCache client for PHP 7.2 by the following link https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.2/latest-64bit you might have an issue with backward compatibility between clients for PHP 7.2 and PHP 7.0. with **consistent distribution**.

PHP 7.0 & ElastiCache 
(libmemcahed 1.0.18)
![image](https://user-images.githubusercontent.com/10096659/58107941-96df5980-7bf3-11e9-89df-b50717157a83.png)

PHP 7.2 & ElastiCache (downgraded libmemcached 1.0.8) 
*old configuration with broken consistent distribution backward compatability
![image](https://user-images.githubusercontent.com/10096659/58107994-a9f22980-7bf3-11e9-803c-3e5be6f2a393.png)

Please pay attention if you are using **consistent distribution**
```
$client = new Memcached();
$client->setOption(Memcached::OPT_DISTRIBUTION, Memcached::DISTRIBUTION_CONSISTENT);
````
you might have different behavior with the mentioned option!

* How to fix it?
You can build your own extension for PHP 7.2 with libmemcached version 1.0.18 by the following solution: https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/issues/19#issuecomment-450203705

**Comment by yzhaon** [comment]
ElastiCache memcached client for PHP 7.2 built against libmemcached 1.0.18 have been released to the public S3 bucket. 

Steps to download the client are here https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.Downloading.html  

Closing this issue.
