### ISSUE TITLE
Compile Error: /usr/local/lib/libmemcached.a: could not read symbols: Bad value

### ISSUE THREAD

**Issue by sethryder** [awslabs/aws-elasticache-cluster-client-memcached-for-php#3]
Hello,

I am attempting to compile the aws-elasticache-cluster-client for PHP 7.0.4.

I have attempted to build it both on the Amazon Linux AMI (Latest) and a normal CentOS 6.7 image and it errors with: 

```
*** Warning: Linking the shared library memcached.la against the
*** static library /usr/local/lib/libmemcached.a is not portable!
libtool: link: cc -shared  .libs/php_memcached.o .libs/php_libmemcached_compat.o .libs/g_fmt.o fastlz/.libs/fastlz.o .libs/php_memcached_session.o   -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/lib -lz /usr/local/lib/libmemcached.a -lcrypt -lpthread -lm -lstdc++ -lsasl2 /usr/local/lib/libmemcachedutil.so /usr/local/lib/libmemcached.so  -Wl,-rpath -Wl,/usr/local/lib   -pthread -Wl,-soname -Wl,memcached.so -o .libs/memcached.so
/usr/bin/ld: /usr/local/lib/libmemcached.a(libmemcached_libmemcached_la-allocators.o): relocation R_X86_64_32S against `_Z20_libmemcached_mallocPK12memcached_stmPv' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libmemcached.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [memcached.la] Error 1
```

I am attempting to build it statically so I can use it on different hosts. Here is the ./configure line:

```
./configure --with-libmemcached-dir=/usr/local --disable-memcached-sasl
```

Along with the MEMCACHED_SHARED_LIBADD line:

```
MEMCACHED_SHARED_LIBADD = -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lz /usr/local/lib/libmemcached.a -lcrypt -lpthread -lm -lstdc++ -lsasl2 -lmemcachedutil
```

I am also using aws-elasticache-cluster-client-libmemcached to compile against. Also I have verified that I am using the proper php7 branch.

**Comment by sethryder** [comment]
FWIW I also just tried it on Ubuntu 14.04 LTS with the same result.

**Comment by QuChen88** [comment]
Please try to dynamically link libmemcached during compilation with the updated instructions in README file.

**Comment by sethryder** [comment]
It does work when I dynamically link libmemcached.

I am guessing statically building the module is no longer supported in PHP 7 (wanted to easily move it inbetween hosts).

**Comment by QuChen88** [comment]
I updated the README instructions for compilation/installation as per previous threads
