### ISSUE TITLE
Is there any chance we can get a newer .so built against libmemcached 1.0.18 current .so are built against 1.0.8

### ISSUE THREAD

**Issue by duronrulez** [awslabs/aws-elasticache-cluster-client-memcached-for-php#30]
Is there any chance we can get a newer .so built against libmemcached 1.0.18. Current .so are built against 1.0.8. Current solution is to build your own .so from source, but thats not ideal.

**Comment by browseman** [comment]
+1

**Comment by antydemant** [comment]
+1

If you use ```DISTRIBUTION_CONSISTENT``` option you should know that the client with libmemcached 1.0.18 is not backward compatible with client which built with libmemcached 1.0.8
#28

**Comment by bensebborn** [comment]
+1

**Comment by yzhaon** [comment]
Which PHP version is this issue referring to?

The PHP 7.2 client has been updated to link against libmemcached 1.0.18

**Comment by duronrulez** [comment]
Our use case was php 7.2

**Comment by yzhaon** [comment]
The PHP 7.2 client has been updated and published. 

You can grab the latest client following these steps https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.Downloading.html

Going to resolve this issue now.

**Comment by duronrulez** [comment]
What about php 7.4? php 7.2 is already out of support
