### ISSUE TITLE
Readme needs an update for the static linking

### ISSUE THREAD

**Issue by duronrulez** [awslabs/aws-elasticache-cluster-client-memcached-for-php#31]
Original:

 ```
Note: you can statically link the libmemcached library into the PHP binary so it can be ported across various Linux platforms. To do that, run the following command, otherwise proceed to "make"
 
 sed -i "s#-lmemcached#<libmemcached build directory>/lib/libmemcached.a -lcrypt -lpthread -lm -lstdc++ -lsasl2#" Makefile
 
 make
```

But that make the new extension die looking for libmemcachedutil

> [03-Oct-2019 09:23:36 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'new_memcached.so' (tried: /xxxx/new_memcached.so (libmemcachedutil.so.2: cannot open shared object file: No such file or directory), 
>.........................

We needed to additionally statically link libmemcachedutil, before the make:

` sed -i "s#-lmemcachedutil#-lz <libmemcached build directory>/lib/libmemcachedutil.a#" Makefile`

**Note: We are building against the aws libmemcached 1.0.18 branch**
Maybe its worth updating the readme for everyone else that find this issue.

**Comment by yuetang95** [comment]
Thanks for your report, it updated in the latest branch.
