### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by AdrienPoupa** [awslabs/aws-elasticache-cluster-client-memcached-for-php#32]
PHP 7.4 stable is now released, could we please get support for it?

**Comment by sodabrew** [comment]
And indeed, take note I released memcached 3.1.5 last week: https://pecl.php.net/package/memcached/3.1.5

**Comment by wadewomersley** [comment]
We'd love to upgrade to 7.4 as soon as possible too - already moved development environments over in preparation.

**Comment by kgkg** [comment]
Any ETA for PHP 7.4 support? It's been 3 months already.

**Comment by KiNgMaR** [comment]
If you feel adventurous, you are invited to try building your own `memcached.so` using the (Docker-based) script that we came up with today: https://github.com/Planerio/aws-elasticache-cluster-client-build
It supports PHP 7.1 through to 7.4 and optionally igbinary. We only tested on Debian-based systems so far, so some feedback from Fedora-based systems would be appreciated.

**Comment by Seegras** [comment]
Ubuntu 20.04 LTS is out, and with it comes PHP 7.4. When the first point release (20.04.1) hits in July or so, all 18.04 LTS systems will want to upgrade. So you might want to make sure support for PHP 7.4. is available at that date the latest.

**Comment by Seegras** [comment]
Ubuntu 20.04 LTS is available on AWS, which means we're now starting to set up systems with that OS version. But here's aws-elasticache-cluster-client-memcached still missing.

**Comment by theoc31** [comment]
> If you feel adventurous, you are invited to try building your own `memcached.so` using the (Docker-based) script that we came up with today: https://github.com/Planerio/aws-elasticache-cluster-client-build
> It supports PHP 7.1 through to 7.4 and optionally igbinary. We only tested on Debian-based systems so far, so some feedback from Fedora-based systems would be appreciated.

Thanks for this. Built the binary using your Docker script and working on CentOS for me.

**Comment by bhavinrshah** [comment]
We have tried on PHP 7.4.11 on Cent OS using https://github.com/Planerio/aws-elasticache-cluster-client-build but memcached could not recognized in PHP.
Can someone help on the same?

**Comment by gabriserra** [comment]
Hi everyone! I have tried the Docker script provided bu Planerio but unfortunately binary does not work in my setup.

So if any of you need the PHP 7.4 memcached I have compiled starting from the main Amazon tree on an Amazon Linux 2 machine and I can assure it works (tested on a production machine based on another Amazon Linux 2). Both libmemcached and libmemcachedutil are statically linked so you can move the .so without issues.

N.B. It is compiled with igbinary support

[AmazonElastiCacheClusterClient-PHP-64bit.zip](https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/files/5580747/AmazonElastiCacheClusterClient-PHP-64bit.zip)

Hope you can save some time... I've spent the entire evening!

**Comment by wired00** [comment]
Any update on this? Is there some way to get amazon-elasticache-cluster-client.so running with PHP 7.4? PHP 7.3 is end of life 28 Nov 2021

**Comment by sngo08** [comment]
Hello,
no updates here?
I tried to compile using @KiNgMaR script but had this following error :
```
/var/www $ php -v
[11-Feb-2021 14:09:58 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'amazon-elasticache-cluster-client.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/amazon-elasticache-cluster-client.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20190902/amazon-elasticache-cluster-client.so: __gxx_personality_v0: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/amazon-elasticache-cluster-client.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/amazon-elasticache-cluster-client.so.so: No such file or directory)) in Unknown on line 0
```
I don't understand why

**Comment by KiNgMaR** [comment]
We just updated https://github.com/Planerio/aws-elasticache-cluster-client-build:

- PHP 8.0 support added
- Alternative build on Amazon Linux 2 available (see instructions in README)

Feedback welcome!

@sngo08: the error likely means that the built binary is not compatible with the Linux distribution you are trying to run it on.

**Comment by sngo08** [comment]
> We just updated https://github.com/Planerio/aws-elasticache-cluster-client-build:
> 
> * PHP 8.0 support added
> * Alternative build on Amazon Linux 2 available (see instructions in README)
> 
> Feedback welcome!
> 
> @sngo08: the error likely means that the built binary is not compatible with the Linux distribution you are trying to run it on.

Thank you ! 
I'm trying to run on Alpine. I thought it would compatible..

**Comment by theoc31** [comment]
> We just updated https://github.com/Planerio/aws-elasticache-cluster-client-build:
> 
> * PHP 8.0 support added
> * Alternative build on Amazon Linux 2 available (see instructions in README)
> 
> Feedback welcome!
> 
> @sngo08: the error likely means that the built binary is not compatible with the Linux distribution you are trying to run it on.

Thanks for this. Built it successfully on CentOS 7.

**Comment by theoc31** [comment]
For CentOS 7 users you're welcome to use my binaries I've built.

PHP 7.4 (tested in production) - https://1drv.ms/u/s!AoMdur8ShlA65CN42LZirhIcibf_?e=F70BqM
PHP 8.0 (not tested in production yet) - https://1drv.ms/u/s!AoMdur8ShlA65CIWgMCdXih2GhGc?e=PfgId6

**Comment by yuetang95** [comment]
Hi all, 

We just updated the PHP 7.4 support. If you want build it from source code, you can use it following the branch `php 7.4`. If you'd like to use the pre-compiled client artifact, you can download it from https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.4/latest-64bit-X86 or https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.4/latest-64bit-arm. 

Thanks.
