### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by comalle23** [awslabs/aws-elasticache-cluster-client-memcached-for-php#36]
probably shouldn't hold my breath since there's still no "official" 7.4 release, but, well, here we are.

**Comment by theoc31** [comment]
For un-official support see #32

**Comment by HairyDuck** [comment]
I'm being forced to update the deprecated ElasticBeanstalk environment "PHP 7.2 running on 64bit Amazon Linux/2.9.18" to "PHP 8.0 running on 64bit Amazon Linux 2/3.3.0" but there isn't an Elasticache autodiscovery client for this version. AWS how do you propose I migrate my applications if your elasticache client isn't supported?

**Comment by exptom** [comment]
Are we likely to get official support @yuetang95 ?

**Comment by placeposition** [comment]
@HairyDuck - me too.

**Comment by barshaul** [comment]
Added support #42
