### ISSUE TITLE
php7 make fail

### ISSUE THREAD

**Issue by greggreenhaw** [awslabs/aws-elasticache-cluster-client-memcached-for-php#4]
Makefile:194: recipe for target 'php_memcached.lo' failed
make: *** [php_memcached.lo] Error 1

**Comment by QuChen88** [comment]
I haven't come across this error previously. Can you please post the exact steps to reproduce this error? i.e. which AMI in EC2 did you launch, and what commands are executed after launching the instance to arrive at the error.

**Comment by greggreenhaw** [comment]
In debian 8, I cloned the php7 branch ran phpize and configured fine without error then on make I got the error. It was confirmed by AWS support as well in ticket 1689381041.

**Comment by QuChen88** [comment]
I just tried to compile on Debian 8 and realized that you will encounter this error if you try to compile the client with the "master" code branch of the package which is intended for PHP 5.x. I switched over to "php7" code branch and it compiled successfully.

**Comment by greggreenhaw** [comment]
i did a git clone -b php7 wouldn't that get the right branch? Can you share a .so file?

**Comment by QuChen88** [comment]
I did 

> git clone https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php.git
> cd aws-elasticache-cluster-client-memcached-for-php
> git checkout php7

You can also do "git config -l" to see which remote upstream you are tracking on your local git branch. 

Let me know if you see any other issues compiling.

**Comment by greggreenhaw** [comment]
root@sample:/usr/local/src/aws-elasticache-cluster-client-memcached-for-php# git checkout php7
Already on 'php7'
Your branch is up-to-date with 'origin/php7'.

**Comment by greggreenhaw** [comment]
phpize && ./configure --with-libmemcached-dir=/usr/ --disable-memcached-sasl --enable-memcached-json && make

**Comment by QuChen88** [comment]
You need to compile and reference our custom libmemcached rather than referencing the libmemcached that is installed in the OS via apt-get.  

I attached my compiled memcached.so artifact here from my compilation earlier today. You can unzip it and try to link this extension in your PHP7 installation and see if this works for you or not. It worked on my Debian 8 machine.

[memcached.zip](https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/files/184043/memcached.zip)

**Comment by greggreenhaw** [comment]
Copying the .so worked

**Comment by QuChen88** [comment]
Sounds good.

**Comment by QuChen88** [comment]
Removing the zip file here in favour of the updated README instructions.
