### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by granadeeu** [awslabs/aws-elasticache-cluster-client-memcached-for-php#45]
Are there any plans for PHP 8.2 support?

**Comment by fabiomsouto** [comment]
Wondering if there's any news on this?

**Comment by granadeeu** [comment]
@fabiomsouto : You can now download the client for PHP 8.2 in AWS. Unfortunately there was no information that it was made available?

**Comment by bystro** [comment]
It's been PHP 8.3 released already :)

**Comment by Wicaeed** [comment]
FWIW PHP 8.2 is listed as supported in AWS documentation
