### ISSUE TITLE
libcrypt.so.2 => not found - PHP 8.2 - Ubuntu 20

### ISSUE THREAD

**Issue by mavwolverine** [awslabs/aws-elasticache-cluster-client-memcached-for-php#48]
On startup PHP says failed to load the lib since libcrypt.so.2 not found.

How do I get this lib? I only seem to find instructions on libcrypt.so.1.

Thanks

**Comment by QuChen88** [comment]
This is usually indicative of the version of the Linux OS that you are running on. `libcrypt.so.1` is on some of the older Linux distro. You can check under `/lib` to see which version of libcrypto you have. 

Have you tried to compile this client extension from source on your Ubuntu server? That should pick up whatever version of libcrypto you have and use it.

**Comment by mavwolverine** [comment]
Not sure what happened. I recreated the instance and this time it just worked. I checked with ldd and this time it was looking for libcrypt.so.1.
